import os
import secrets
import textwrap

import asyncpg
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.security import hash_password, is_forbidden_username
from app.models.user import User, Department, ForbiddenUsername
from app.schemas.auth import InitRequest
from app.schemas.system import DbTestRequest, ConfigureRequest

router = APIRouter()

FORBIDDEN_SEED = [
    "admin", "root", "administrator", "superuser", "sysadmin",
    "sa", "dba", "test", "guest", "user", "manager", "system",
    "ops", "operator", "service", "daemon",
]


@router.post("/test-db")
async def test_db(body: DbTestRequest):
    """Test a PostgreSQL connection with the given credentials (no auth required)."""
    try:
        conn = await asyncpg.connect(
            host=body.host,
            port=body.port,
            database=body.db_name,
            user=body.db_user,
            password=body.db_password,
            timeout=5,
        )
        version: str = await conn.fetchval("SELECT version()")
        await conn.close()
        # Return only major version info — do not echo credentials
        pg_ver = version.split(",")[0] if version else "PostgreSQL"
        return {"success": True, "version": pg_ver}
    except asyncpg.InvalidPasswordError:
        return {"success": False, "error": "인증 실패 — 사용자명 또는 비밀번호를 확인하세요."}
    except asyncpg.InvalidCatalogNameError:
        return {"success": False, "error": f"데이터베이스 '{body.db_name}'를 찾을 수 없습니다."}
    except OSError:
        return {"success": False, "error": f"{body.host}:{body.port} 에 연결할 수 없습니다."}
    except Exception as e:
        return {"success": False, "error": str(e)[:200]}


@router.post("/configure")
async def configure(body: ConfigureRequest):
    """Write .env file with DB and web port settings (setup wizard only)."""
    env_content = textwrap.dedent(f"""\
        # Auto-generated by DWSU Mini-ERP Setup Wizard
        APP_ENV=production
        SECRET_KEY={secrets.token_hex(32)}
        APP_PORT=8080

        DB_HOST={body.db_host}
        DB_PORT={body.db_port}
        DB_NAME={body.db_name}
        DB_USER={body.db_user}
        DB_PASSWORD={body.db_password}

        WEB_PORT={body.web_port}

        SESSION_EXPIRE_HOURS=4
        BCRYPT_ROUNDS=12
        MAX_LOGIN_ATTEMPTS=5
        LOCKOUT_MINUTES=15

        ALLOWED_ORIGINS=http://localhost:{body.web_port}
    """)
    env_path = os.path.join(os.path.dirname(__file__), "..", "..", "..", ".env")
    env_path = os.path.normpath(env_path)
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)
    return {"message": ".env 설정 파일이 저장되었습니다."}


@router.get("/status")
async def status(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(User).where(User.is_system_admin.is_(True)))
    initialized = result.scalar_one_or_none() is not None
    return {"initialized": initialized}


@router.post("/initialize")
async def initialize(body: InitRequest, db: AsyncSession = Depends(get_db)):
    existing = await db.execute(select(User).where(User.is_system_admin.is_(True)))
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=403, detail="이미 초기화된 시스템입니다.")

    if is_forbidden_username(body.admin_username):
        raise HTTPException(
            status_code=400,
            detail=f"'{body.admin_username}'은(는) 사용 불가능한 아이디입니다. 기본 계정명은 사용할 수 없습니다.",
        )

    if body.password != body.confirm_password:
        raise HTTPException(status_code=400, detail="비밀번호가 일치하지 않습니다.")

    for name in FORBIDDEN_SEED:
        db.add(ForbiddenUsername(username=name))

    dept = Department(dept_code="SYS", dept_name="시스템관리")
    db.add(dept)
    await db.flush()

    db.add(User(
        username=body.admin_username,
        password_hash=hash_password(body.password),
        display_name=body.display_name,
        dept_id=dept.dept_id,
        is_system_admin=True,
        is_active=True,
    ))

    return {"message": "시스템 초기화가 완료되었습니다."}


@router.get("/menus")
async def list_menus(db: AsyncSession = Depends(get_db)):
    from sqlalchemy.orm import selectinload
    from app.models.menu import MainMenu
    result = await db.execute(
        select(MainMenu)
        .where(MainMenu.is_active.is_(True))
        .options(selectinload(MainMenu.sub_menus))
        .order_by(MainMenu.sort_order)
    )
    menus = result.scalars().all()
    return [
        {
            "id": str(m.menu_id),
            "code": m.menu_code,
            "name": m.menu_name,
            "icon": m.menu_icon,
            "subMenus": [
                {
                    "id": str(s.sub_menu_id),
                    "code": s.sub_menu_code,
                    "name": s.sub_menu_name,
                    "routePath": s.route_path,
                }
                for s in m.sub_menus if s.is_active
            ],
        }
        for m in menus
    ]
